from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplacePackage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("package_id", models.CharField(max_length=64, unique=True)),
                ("code", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("subcategory", models.CharField(blank=True, max_length=255)),
                ("passing_score", models.FloatField(default=90.0)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("question_count", models.PositiveIntegerField(default=0)),
                ("domains", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                ("questions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name"], "verbose_name_plural": "categories"},
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name"], "verbose_name_plural": "subcategories"},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("passing_score", models.FloatField(default=90.0)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("question_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="exams", to="webapp.category")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("subcategory", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="exams", to="webapp.subcategory")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="ExamDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("weight", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exam", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="domains", to="webapp.exam")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qid", models.CharField(max_length=255)),
                ("type", models.CharField(choices=[("multiple_choice", "Multiple choice"), ("drag_and_drop", "Drag and drop")], max_length=32)),
                ("question", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                ("reference_url", models.URLField(blank=True)),
                ("correct_explanation", models.TextField(blank=True)),
                ("exhibit_image", models.CharField(blank=True, max_length=500)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("ativa", "Ativa"), ("rascunho", "Rascunho"), ("em_revisao", "Em revisão"), ("obsoleta", "Obsoleta"), ("arquivada", "Arquivada")], default="ativa", max_length=24)),
                ("banca", models.CharField(blank=True, max_length=255)),
                ("year", models.CharField(blank=True, max_length=16)),
                ("orgao", models.CharField(blank=True, max_length=255)),
                ("cargo", models.CharField(blank=True, max_length=255)),
                ("disciplina", models.CharField(blank=True, max_length=255)),
                ("assunto", models.CharField(blank=True, max_length=255)),
                ("subassunto", models.CharField(blank=True, max_length=255)),
                ("escolaridade", models.CharField(blank=True, max_length=255)),
                ("contest_status", models.CharField(blank=True, max_length=32)),
                ("allow_multiple", models.BooleanField(default=False)),
                ("items", models.JSONField(blank=True, default=list)),
                ("targets", models.JSONField(blank=True, default=list)),
                ("correct_mapping", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="questions", to="webapp.category")),
                ("domain", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="questions", to="webapp.examdomain")),
                ("exam", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="questions", to="webapp.exam")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("subcategory", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="questions", to="webapp.subcategory")),
                ("tags", models.ManyToManyField(blank=True, related_name="questions", to="webapp.tag")),
            ],
            options={"ordering": ["qid"]},
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="options", to="webapp.question")),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mode", models.CharField(choices=[("study", "Study"), ("real", "Real exam")], default="real", max_length=16)),
                ("passing_score", models.FloatField(default=90.0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("answered", models.PositiveIntegerField(default=0)),
                ("correct", models.PositiveIntegerField(default=0)),
                ("wrong", models.PositiveIntegerField(default=0)),
                ("percent", models.FloatField(default=0)),
                ("approved", models.BooleanField(default=False)),
                ("focus_tags", models.JSONField(blank=True, default=list)),
                ("qids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("exam", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="simulations", to="webapp.exam")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-finished_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="SimulationAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qid", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("subcategory", models.CharField(blank=True, max_length=255)),
                ("exam", models.CharField(blank=True, max_length=255)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("question_text", models.TextField(blank=True)),
                ("explanation", models.TextField(blank=True)),
                ("reference_url", models.URLField(blank=True)),
                ("correct_explanation", models.TextField(blank=True)),
                ("wrong_explanations", models.JSONField(blank=True, default=dict)),
                ("question_version", models.PositiveIntegerField(default=1)),
                ("question_status", models.CharField(blank=True, max_length=24)),
                ("exhibit_image", models.CharField(blank=True, max_length=500)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("user_answer", models.TextField(blank=True)),
                ("correct_answer", models.TextField(blank=True)),
                ("confidence_level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_correct", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("question", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="simulation_attempts", to="webapp.question")),
                ("simulation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="webapp.simulation")),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="QuestionAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qid", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                ("confidence_level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("question", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="question_attempts", to="webapp.question")),
                ("simulation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="question_attempts", to="webapp.simulation")),
            ],
            options={"ordering": ["-answered_at"]},
        ),
        migrations.CreateModel(
            name="UserQuestionStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answers", models.PositiveIntegerField(default=0)),
                ("correct", models.PositiveIntegerField(default=0)),
                ("wrong", models.PositiveIntegerField(default=0)),
                ("correct_streak", models.PositiveIntegerField(default=0)),
                ("wrong_streak", models.PositiveIntegerField(default=0)),
                ("last_confidence_level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("review_priority", models.PositiveIntegerField(default=0)),
                ("last_answered_at", models.DateTimeField(blank=True, null=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_stats", to="webapp.question")),
            ],
        ),
        migrations.AddIndex(model_name="category", index=models.Index(fields=["owner", "name"], name="webapp_cate_owner_i_3127d2_idx")),
        migrations.AddIndex(model_name="subcategory", index=models.Index(fields=["owner", "name"], name="webapp_subc_owner_i_1db1dd_idx")),
        migrations.AddIndex(model_name="tag", index=models.Index(fields=["owner", "name"], name="webapp_tag_owner_i_20d176_idx")),
        migrations.AddIndex(model_name="exam", index=models.Index(fields=["owner", "name"], name="webapp_exam_owner_i_637eba_idx")),
        migrations.AddIndex(model_name="examdomain", index=models.Index(fields=["exam", "name"], name="webapp_exam_exam_id_dfdbd0_idx")),
        migrations.AddIndex(model_name="question", index=models.Index(fields=["owner", "qid"], name="webapp_ques_owner_i_3e1078_idx")),
        migrations.AddIndex(model_name="simulation", index=models.Index(fields=["owner", "finished_at"], name="webapp_simu_owner_i_d8a606_idx")),
        migrations.AddIndex(model_name="questionattempt", index=models.Index(fields=["owner", "qid"], name="webapp_ques_owner_i_1a86b4_idx")),
        migrations.AddIndex(model_name="userquestionstats", index=models.Index(fields=["owner", "question"], name="webapp_user_owner_i_0f5f95_idx")),
        migrations.AddConstraint(model_name="tag", constraint=models.UniqueConstraint(fields=("owner", "name"), name="uniq_tag_owner_name")),
        migrations.AddConstraint(model_name="category", constraint=models.UniqueConstraint(fields=("owner", "name"), name="uniq_category_owner_name")),
        migrations.AddConstraint(model_name="subcategory", constraint=models.UniqueConstraint(fields=("owner", "name"), name="uniq_subcategory_owner_name")),
        migrations.AddConstraint(model_name="exam", constraint=models.UniqueConstraint(fields=("owner", "name"), name="uniq_exam_owner_name")),
        migrations.AddConstraint(model_name="examdomain", constraint=models.UniqueConstraint(fields=("exam", "name"), name="uniq_exam_domain_name")),
        migrations.AddConstraint(model_name="question", constraint=models.UniqueConstraint(fields=("owner", "qid"), name="uniq_question_owner_qid")),
        migrations.AddConstraint(model_name="userquestionstats", constraint=models.UniqueConstraint(fields=("owner", "question"), name="uniq_user_question_stats")),
    ]
